version: "3.7"
services:
  api_service:
    build: .
    restart: always
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
  postgres_db:
    image: "postgres:11.4"
    container_name: db
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: java_app_db
      POSTGRES_PASSWORD: 12345